<?php
return array (
  'name' => 
  array (
    'fieldid' => '109',
    'modelid' => '10',
    'siteid' => '0',
    'field' => 'name',
    'name' => '真实姓名',
    'tips' => '',
    'css' => '',
    'minlength' => '2',
    'maxlength' => '12',
    'pattern' => '',
    'errortips' => '请输入真实姓名',
    'formtype' => 'text',
    'setting' => 'array (
  \'size\' => \'15\',
  \'defaultvalue\' => \'\',
  \'ispassword\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '1',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '15',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'tel' => 
  array (
    'fieldid' => '108',
    'modelid' => '10',
    'siteid' => '0',
    'field' => 'tel',
    'name' => '手机号码',
    'tips' => '',
    'css' => '',
    'minlength' => '11',
    'maxlength' => '11',
    'pattern' => '/^(1)[0-9]{10}$/',
    'errortips' => '为了方便我们联系，请输入正确的手机号',
    'formtype' => 'text',
    'setting' => 'array (
  \'size\' => \'15\',
  \'defaultvalue\' => \'\',
  \'ispassword\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '2',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '15',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'diqu' => 
  array (
    'fieldid' => '112',
    'modelid' => '10',
    'siteid' => '0',
    'field' => 'diqu',
    'name' => '地区',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '/^[0-9.-]+$/',
    'errortips' => '请选择你所在地区',
    'formtype' => 'linkage',
    'setting' => 'array (
  \'linkageid\' => \'1\',
  \'showtype\' => \'2\',
  \'space\' => \'\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '3',
    'disabled' => '0',
    'isomnipotent' => '0',
    'linkageid' => '1',
    'showtype' => '2',
    'space' => '',
  ),
  'qq' => 
  array (
    'fieldid' => '110',
    'modelid' => '10',
    'siteid' => '0',
    'field' => 'qq',
    'name' => 'QQ',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '20',
    'pattern' => '/^[0-9]{5,20}$/',
    'errortips' => '请输入正确的QQ号',
    'formtype' => 'text',
    'setting' => 'array (
  \'size\' => \'15\',
  \'defaultvalue\' => \'\',
  \'ispassword\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '4',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '15',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'weixin' => 
  array (
    'fieldid' => '111',
    'modelid' => '10',
    'siteid' => '0',
    'field' => 'weixin',
    'name' => '微信',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '20',
    'pattern' => '',
    'errortips' => '请输入正确的微信号',
    'formtype' => 'text',
    'setting' => 'array (
  \'size\' => \'15\',
  \'defaultvalue\' => \'\',
  \'ispassword\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '5',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '15',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'birthday' => 
  array (
    'fieldid' => '83',
    'modelid' => '10',
    'siteid' => '1',
    'field' => 'birthday',
    'name' => '生日',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '生日格式错误',
    'formtype' => 'datetime',
    'setting' => 'array (
  \'fieldtype\' => \'date\',
  \'format\' => \'Y-m-d\',
  \'defaulttype\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '1',
    'isposition' => '0',
    'listorder' => '6',
    'disabled' => '0',
    'isomnipotent' => '0',
    'fieldtype' => 'date',
    'format' => 'Y-m-d',
    'defaulttype' => '0',
  ),
);
?>