<?php
return array (
  10 => 
  array (
    'modelid' => '10',
    'siteid' => '1',
    'name' => '普通会员',
    'description' => '普通会员',
    'tablename' => 'member_detail',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => '',
    'category_template' => '',
    'list_template' => '',
    'show_template' => '',
    'js_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '2',
  ),
  12 => 
  array (
    'modelid' => '12',
    'siteid' => '1',
    'name' => '门店会员',
    'description' => '',
    'tablename' => 'member_mendian',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => '',
    'category_template' => '',
    'list_template' => '',
    'show_template' => '',
    'js_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '2',
  ),
  13 => 
  array (
    'modelid' => '13',
    'siteid' => '1',
    'name' => '企业会员',
    'description' => '',
    'tablename' => 'member_qiye',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => '',
    'category_template' => '',
    'list_template' => '',
    'show_template' => '',
    'js_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '2',
  ),
);
?>